// SPDX-License-Identifier: MIT
// Copyright (C) 2026 SukramJ

package coordinator

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"log/slog"
	"os"
	"path/filepath"
	"reflect"
	"sort"
	"strings"
	"testing"

	hacatalog "github.com/SukramJ/go-ha-catalog"
	"github.com/SukramJ/go-hamqtt/discovery"
	mqtt "github.com/SukramJ/go-mqtt"

	"github.com/SukramJ/go-unifi2mqtt/internal/config"
	"github.com/SukramJ/go-unifi2mqtt/internal/hass"
	"github.com/SukramJ/go-unifi2mqtt/internal/model"
	"github.com/SukramJ/go-unifi2mqtt/internal/unifi"
)

// The byte-equality proof — ADR 0070 phase 9, step 4.
//
// The question this file answers is the one the whole phase turns on:
// does go-hamqtt reproduce this bridge's published discovery payloads
// exactly, before step 6 makes the move irreversible? It is answered
// against the five pinned goldens on disk — never against the builders
// the library would replace, and never against a fixture this file
// regenerates. Nothing here consults -update-surface-golden; the flag
// is not reachable from any function in this file, and the five
// SHA-256 literals in surface_pin_test.go are untouched by this PR.
//
// Nothing published. [failingPublisher] is the assertion of that rather
// than a promise in a comment, and it drives every entry point the new
// path has.

// --- reading the pins ------------------------------------------------

// goldenConfigs returns a scenario's discovery plane as pinned on disk:
// config topic -> canonical encoding of the payload.
//
// It reads the golden FILE and never the builders. A comparison against
// output regenerated by the code under test proves only that the
// regeneration ran.
func goldenConfigs(t *testing.T, scenario string) map[string]string {
	t.Helper()
	path := filepath.Join("testdata", "surface", scenario+".json")
	raw, err := os.ReadFile(path) //nolint:gosec // fixed test fixture path
	if err != nil {
		t.Fatalf("read golden %s: %v", path, err)
	}
	var doc surfaceDoc
	if err := json.Unmarshal(raw, &doc); err != nil {
		t.Fatalf("decode golden %s: %v", path, err)
	}
	out := map[string]string{}
	for _, m := range doc.Messages {
		if !isConfigTopic(m.Topic) {
			continue
		}
		if m.JSON == nil {
			t.Fatalf("%s: config message %q carries no decoded payload", scenario, m.Topic)
		}
		b, err := json.Marshal(m.JSON)
		if err != nil {
			t.Fatalf("%s: re-encode %q: %v", scenario, m.Topic, err)
		}
		out[m.Topic] = string(b)
	}
	if len(out) == 0 {
		t.Fatalf("%s: the golden pins no discovery config at all", scenario)
	}
	return out
}

// canonicalBody re-encodes a rendered payload so both sides of every
// comparison are on the same footing: sorted keys, no formatting.
func canonicalBody(t *testing.T, body []byte) string {
	t.Helper()
	var obj map[string]any
	if err := json.Unmarshal(body, &obj); err != nil {
		t.Fatalf("rendered body is not JSON: %v\n%s", err, body)
	}
	b, err := json.Marshal(obj)
	if err != nil {
		t.Fatalf("re-encode: %v", err)
	}
	return string(b)
}

func sortedKeys[V any](m map[string]V) []string {
	out := make([]string, 0, len(m))
	for k := range m {
		out = append(out, k)
	}
	sort.Strings(out)
	return out
}

// --- re-deriving the inputs -------------------------------------------

// buildHamqttInputs re-derives the discovery inputs of one scenario:
// the device snapshot the static loop announces from, the clients that
// passed the filter with their uplinks resolved, the SSID catalogue and
// the two option sets, gated exactly as the coordinator gates them.
//
// It re-derives rather than intercepts, which is only safe because
// TestHamqttInputsReproduceThePublishedConfigTopics feeds the same
// value to the SHIPPED builders and requires the golden back. A
// re-derivation that quietly differed — one client filtered out, one
// control off — would render a smaller entity set and let the
// byte-equality below prove something smaller than it claims.
func buildHamqttInputs(t *testing.T, sc surfaceScenario) hass.HamqttFleet {
	t.Helper()

	cfg, err := config.Load(strings.NewReader(sc.yaml), config.MapEnv{})
	if err != nil {
		t.Fatalf("scenario %s: config: %v", sc.name, err)
	}
	src := newFakeSource()
	sc.setup(src)
	if !cfg.ClassicEnable {
		src.healthErr = unifi.ErrCapabilityUnavailable
	}
	caps := capSet{}
	for _, c := range sc.caps {
		caps[c] = true
	}

	c := New(Deps{
		Cfg:          cfg,
		Site:         model.Site{ID: "site-uuid", Name: "Default", Internal: "default"},
		Source:       src,
		MQTT:         &fakeBroker{},
		Capabilities: caps,
		Info:         model.ControllerInfo{ApplicationVersion: "10.5.67"},
		Logger:       slog.New(slog.DiscardHandler),
		Now:          newFakeClock().now,
	})

	ctx := context.Background()
	// The static loop is what populates the detail snapshot, the
	// network catalogue and the device-id index the client filter and
	// the uplink resolution both read.
	if err := c.refreshStatic(ctx); err != nil {
		t.Fatalf("scenario %s: refreshStatic: %v", sc.name, err)
	}

	devices, err := src.DevicesWithDetails(ctx, c.site.ID)
	if err != nil {
		t.Fatalf("scenario %s: DevicesWithDetails: %v", sc.name, err)
	}
	wlans, err := src.WLANs(ctx, c.site.ID)
	if err != nil {
		t.Fatalf("scenario %s: WLANs: %v", sc.name, err)
	}

	var clients []model.Client
	if cfg.Clients.Enable {
		all, err := src.Clients(ctx, c.site.ID)
		if err != nil {
			t.Fatalf("scenario %s: Clients: %v", sc.name, err)
		}
		c.mu.RLock()
		networks, byID := c.networks, c.deviceIDToMAC
		c.mu.RUnlock()
		for i := range all {
			if id := all[i].UplinkID; id != "" {
				all[i].UplinkMAC = byID[id]
			}
		}
		clients = newClientFilter(&cfg.Clients, networks, slog.New(slog.DiscardHandler)).Apply(all)
	}

	return hass.HamqttFleet{
		Devices:        devices,
		Clients:        clients,
		WLANs:          wlans,
		ClientOpts:     hass.ClientOptions{Signal: c.clientSignalEnabled()},
		ControlOpts:    c.controlOptions(),
		AnnounceHealth: cfg.ClassicEnable,
	}
}

// scenarioDiscovery builds the hass.Discovery of one scenario, pointed
// at the same topic layout the coordinator publishes on.
func scenarioDiscovery(t *testing.T, sc surfaceScenario) *hass.Discovery {
	t.Helper()
	cfg, err := config.Load(strings.NewReader(sc.yaml), config.MapEnv{})
	if err != nil {
		t.Fatalf("scenario %s: config: %v", sc.name, err)
	}
	c := New(Deps{
		Cfg:    cfg,
		Site:   model.Site{ID: "site-uuid", Name: "Default", Internal: "default"},
		Source: newFakeSource(),
		MQTT:   failingPublisher{t: t},
		Logger: slog.New(slog.DiscardHandler),
		Now:    newFakeClock().now,
	})
	return hass.New(c.DiscoveryConfig(cfg.HASSBaseTopic, cfg.Language))
}

// shippedConfigs renders the fleet through the SHIPPED builders, in the
// order the coordinator announces them.
func shippedConfigs(t *testing.T, d *hass.Discovery, f hass.HamqttFleet) map[string]string {
	t.Helper()
	out := map[string]string{}
	add := func(entries []hass.Entry) {
		for _, e := range entries {
			if _, dup := out[e.ConfigTopic]; dup {
				t.Fatalf("the shipped builders produced %q twice", e.ConfigTopic)
			}
			out[e.ConfigTopic] = canonicalBody(t, e.Payload)
		}
	}
	for i := range f.Devices {
		dev := &f.Devices[i]
		entries, err := d.Device(dev)
		if err != nil {
			t.Fatalf("Device: %v", err)
		}
		add(entries)
		controls, err := d.DeviceControls(dev, f.ControlOpts)
		if err != nil {
			t.Fatalf("DeviceControls: %v", err)
		}
		add(controls)
	}
	if f.ControlOpts.WLANEnable {
		for i := range f.WLANs {
			entry, err := d.WLANControl(&f.WLANs[i])
			if err != nil {
				t.Fatalf("WLANControl: %v", err)
			}
			add([]hass.Entry{entry})
		}
	}
	for i := range f.Clients {
		cl := &f.Clients[i]
		entries, err := d.Client(cl, f.ClientOpts)
		if err != nil {
			t.Fatalf("Client: %v", err)
		}
		add(entries)
		controls, err := d.ClientControls(cl, f.ControlOpts)
		if err != nil {
			t.Fatalf("ClientControls: %v", err)
		}
		add(controls)
	}
	if f.AnnounceHealth {
		entries, err := d.Health()
		if err != nil {
			t.Fatalf("Health: %v", err)
		}
		add(entries)
	}
	return out
}

// renderedConfigs renders the fleet through go-hamqtt.
func renderedConfigs(t *testing.T, d *hass.Discovery, f hass.HamqttFleet) map[string]string {
	t.Helper()
	comps, err := d.RenderHamqtt(f)
	if err != nil {
		t.Fatalf("RenderHamqtt: %v", err)
	}
	out := make(map[string]string, len(comps))
	for _, c := range comps {
		if _, dup := out[c.Topic]; dup {
			t.Fatalf("the library path rendered %q twice", c.Topic)
		}
		out[c.Topic] = canonicalBody(t, c.Body)
	}
	return out
}

// --- the experiment ---------------------------------------------------

// hamqttTotalConfigs is the whole pinned discovery plane: 315 configs
// across five scenarios.
//
// A Go literal, so shrinking the proof is a declaration in review
// rather than a quietly smaller number in a log line.
const hamqttTotalConfigs = 315

// F15's carve-out used to live here.
//
// Step 4 could not reproduce `"manufacturer": ""` on 36 client configs
// through the library — discovery.DeviceInfo.Manufacturer is
// `omitempty`, so an empty manufacturer renders as an absent key — and
// carved the one key out of the comparison under tight conditions
// rather than forcing it through Component.Extra["device"], which would
// have overridden exactly the part of the payload under test.
//
// The carve-out was temporary by construction and is gone: this bridge
// now omits the key too, so the comparison below is byte-equality on
// all 315 configs with no exceptions at all.

// TestHamqttReproducesThePublishedConfigs is the headline.
func TestHamqttReproducesThePublishedConfigs(t *testing.T) {
	t.Parallel()

	total, matched := 0, 0
	for _, sc := range surfaceScenarios() {
		want := goldenConfigs(t, sc.name)
		f := buildHamqttInputs(t, sc)
		got := renderedConfigs(t, scenarioDiscovery(t, sc), f)

		for _, topic := range sortedKeys(want) {
			total++
			g, ok := got[topic]
			if !ok {
				t.Errorf("%s: - the library renders no payload for the pinned topic %s", sc.name, topic)
				continue
			}
			if g == want[topic] {
				matched++
				continue
			}
			t.Errorf("%s: ~ %s\n  pinned   %s\n  rendered %s", sc.name, topic, want[topic], g)
		}
		for _, topic := range sortedKeys(got) {
			if _, ok := want[topic]; !ok {
				t.Errorf("%s: + the library renders a config this bridge does not publish: %s",
					sc.name, topic)
			}
		}
	}

	if total != hamqttTotalConfigs {
		t.Errorf("compared %d pinned configs, want %d", total, hamqttTotalConfigs)
	}
	if matched != hamqttTotalConfigs {
		t.Errorf("reproduced %d of %d pinned configs byte for byte, with no carve-outs left",
			matched, hamqttTotalConfigs)
	}
	t.Logf("byte-equal: %d of %d", matched, hamqttTotalConfigs)
}

// TestHamqttInputsReproduceThePublishedConfigTopics is what makes the
// proof above non-circular.
//
// buildHamqttInputs re-derives the discovery inputs from a warmed
// coordinator rather than intercepting them at the call site. A
// re-derivation that quietly differed from what the daemon announces
// would render a different entity set, and the comparison above would
// be proving something smaller than it claims. So the same value is fed
// to the SHIPPED builders and the golden is required back, whole.
func TestHamqttInputsReproduceThePublishedConfigTopics(t *testing.T) {
	t.Parallel()

	checked := 0
	for _, sc := range surfaceScenarios() {
		want := goldenConfigs(t, sc.name)
		f := buildHamqttInputs(t, sc)
		got := shippedConfigs(t, scenarioDiscovery(t, sc), f)

		if len(got) != len(want) {
			t.Errorf("%s: the re-derived inputs produce %d configs, the golden pins %d",
				sc.name, len(got), len(want))
		}
		for _, topic := range sortedKeys(want) {
			checked++
			if got[topic] != want[topic] {
				t.Errorf("%s: the re-derived inputs do not reproduce %s\n  golden %s\n  got    %s",
					sc.name, topic, want[topic], got[topic])
			}
		}
	}
	if checked != hamqttTotalConfigs {
		t.Errorf("checked %d configs, want %d", checked, hamqttTotalConfigs)
	}
}

// --- the topic form ---------------------------------------------------

// TestHamqttRetractionReproducesEveryPublishedConfigTopic is F5,
// settled against running code rather than against the documentation.
//
// publisher.SupersededTopics' default form renders
// <prefix>/<platform>/<bundle.NodeID>/<component key>/config. Both
// inputs are step-4 modelling choices, so this asserts the two that
// matter — the node id IS device.identifiers[0] and the component key
// IS the object-id segment — over every config the bridge publishes,
// and asserts that the other candidate form reproduces NONE of them.
// publisher.Config.LegacyEntityTopics REPLACES the default rather than
// extending it, so naming LegacyTopicByUniqueID at step 6 would turn a
// working retraction into no retraction at all.
func TestHamqttRetractionReproducesEveryPublishedConfigTopic(t *testing.T) {
	t.Parallel()

	withNodeID := func(prefix, platform, nodeID, key, _ string) string {
		return prefix + "/" + platform + "/" + nodeID + "/" + key + "/config"
	}
	byUniqueID := func(prefix, platform, _, _, uniqueID string) string {
		return prefix + "/" + platform + "/" + uniqueID + "/config"
	}

	matched, unmatchedByUID, divergentUID := 0, 0, 0
	for _, sc := range surfaceScenarios() {
		want := goldenConfigs(t, sc.name)
		f := buildHamqttInputs(t, sc)
		comps, err := scenarioDiscovery(t, sc).RenderHamqtt(f)
		if err != nil {
			t.Fatalf("RenderHamqtt: %v", err)
		}
		for _, c := range comps {
			var body map[string]any
			if err := json.Unmarshal(c.Body, &body); err != nil {
				t.Fatalf("decode %s: %v", c.Topic, err)
			}
			dev, _ := body["device"].(map[string]any)
			ids, _ := dev["identifiers"].([]any)
			if len(ids) == 0 {
				t.Fatalf("%s: rendered no device identifier", c.Topic)
			}
			identifier, _ := ids[0].(string)
			if c.NodeID != identifier {
				t.Errorf("%s: bundle node id %q is not device.identifiers[0] %q — "+
					"the default retraction form would retract nothing",
					c.Topic, c.NodeID, identifier)
			}
			uniqueID, _ := body["unique_id"].(string)

			parts := strings.Split(c.Topic, "/")
			got := withNodeID(parts[0], string(c.Platform), c.NodeID, c.Key, uniqueID)
			if _, pinned := want[c.Topic]; !pinned {
				t.Fatalf("%s is not a pinned topic", c.Topic)
			}
			if got != c.Topic {
				t.Errorf("the five-segment node-id form renders %q, want %q", got, c.Topic)
				continue
			}
			matched++
			if byUniqueID(parts[0], string(c.Platform), c.NodeID, c.Key, uniqueID) != c.Topic {
				unmatchedByUID++
			}
			if uniqueID != c.NodeID+"_"+c.Key {
				divergentUID++
			}
		}
	}

	if matched != hamqttTotalConfigs {
		t.Errorf("the default form reproduced %d of %d published config topics",
			matched, hamqttTotalConfigs)
	}
	if unmatchedByUID != matched {
		t.Errorf("the by-unique_id form reproduces %d of %d published topics; "+
			"if the two candidates are no longer distinguishable this test proves nothing",
			matched-unmatchedByUID, matched)
	}
	// The 21 of F5: the component key cannot be derived from the unique
	// id, because on these it is not its suffix.
	const wantDivergentUID = 21
	if divergentUID != wantDivergentUID {
		t.Errorf("unique_id != <node_id>_<key> on %d configs, want %d", divergentUID, wantDivergentUID)
	}
	if hass.LegacyConfigTopicForm != "<discovery_prefix>/<platform>/<node_id>/<object_id>/config" {
		t.Errorf("hass.LegacyConfigTopicForm = %q, which is no longer the form this test proves",
			hass.LegacyConfigTopicForm)
	}
}

// TestHamqttBundleWouldBeInvisibleToItsOwnReconcile records the second
// half of F5: this daemon's orphan sweep subscribes to a strictly
// five-segment filter, and a device bundle is four segments.
func TestHamqttBundleWouldBeInvisibleToItsOwnReconcile(t *testing.T) {
	t.Parallel()

	filter := newSurfaceDiscovery(t).ConfigFilter()
	if filter != "homeassistant/+/+/+/config" {
		t.Fatalf("ConfigFilter = %q; this test's premise has changed", filter)
	}
	bundles, err := scenarioDiscovery(t, surfaceScenarios()[2]).
		HamqttBundles(buildHamqttInputs(t, surfaceScenarios()[2]), hamqttOrigin())
	if err != nil {
		t.Fatalf("HamqttBundles: %v", err)
	}
	if len(bundles) == 0 {
		t.Fatal("no bundles rendered")
	}
	for _, b := range bundles {
		topic := b.Topic("homeassistant")
		if matchFilter(filter, topic) {
			t.Errorf("the reconcile filter matches the bundle topic %q; "+
				"F5's second half no longer holds and step 6 needs re-reading", topic)
		}
	}
}

// --- validation --------------------------------------------------------

// hamqttOrigin is the origin every payload carries, per F7. It is the
// production value and not a test literal: a test-only origin would let
// the shipped path and the render path disagree on the one block that
// decides whether a bundle is published at all.
func hamqttOrigin() discovery.Origin { return hass.HamqttOrigin() }

// TestHamqttPayloadsPassDiscoveryValidate runs every rendered payload
// through the schema check the library applies.
//
// The measurement recorded 18 refusals, all `button`, for `state_topic`
// and `optimistic` — two keys the MQTT button schema does not declare,
// emitted because neither of this repository's own struct fields had
// `omitempty`. Step 2 fixed both. This confirms the refusals are gone,
// and it is the check that gates step 6: a blocking result means the
// bundle is not published at all, so the device loses every entity
// rather than one key.
func TestHamqttPayloadsPassDiscoveryValidate(t *testing.T) {
	t.Parallel()

	checked, advisory := 0, 0
	refusals := map[string]int{}
	for _, sc := range surfaceScenarios() {
		comps, err := scenarioDiscovery(t, sc).RenderHamqtt(buildHamqttInputs(t, sc))
		if err != nil {
			t.Fatalf("RenderHamqtt: %v", err)
		}
		for _, c := range comps {
			var body map[string]any
			if err := json.Unmarshal(c.Body, &body); err != nil {
				t.Fatalf("decode %s: %v", c.Topic, err)
			}
			checked++
			err := discovery.ValidateBody(c.Platform, body)
			if err == nil {
				continue
			}
			var ve *discovery.ValidationError
			if errors.As(err, &ve) && !ve.Blocking() {
				advisory++
				t.Logf("%s: advisory: %v", c.Topic, err)
				continue
			}
			refusals[fmt.Sprintf("%s: %v", c.Platform, err)]++
		}
	}
	if checked != hamqttTotalConfigs {
		t.Errorf("validated %d payloads, want %d", checked, hamqttTotalConfigs)
	}
	for _, k := range sortedKeys(refusals) {
		t.Errorf("%d payloads refused: %s", refusals[k], k)
	}
	t.Logf("%d payloads validated: %d refused, %d advisory", checked, len(refusals), advisory)
}

// TestHamqttBundlesValidate is the same question in the form step 6
// would publish, which is the form where a refusal is expensive: an
// invalid bundle publishes nothing at all, so one bad component costs
// its device every entity it has.
//
// It also answers the measurement's open question about
// `device_tracker` as far as a unit test can: three of the 315 configs
// are trackers, a platform no other bridge in the programme publishes,
// and they are carried inside a client's bundle here. What remains is
// the runtime half — whether Home Assistant itself accepts a bundle
// component on that platform — which only a live console can settle.
func TestHamqttBundlesValidate(t *testing.T) {
	t.Parallel()

	bundles, components, trackers := 0, 0, 0
	for _, sc := range surfaceScenarios() {
		rendered, err := scenarioDiscovery(t, sc).
			HamqttBundles(buildHamqttInputs(t, sc), hamqttOrigin())
		if err != nil {
			t.Fatalf("%s: HamqttBundles: %v", sc.name, err)
		}
		for _, b := range rendered {
			bundles++
			components += len(b.Components)
			for _, key := range b.Keys() {
				if b.Components[key].Platform == hacatalog.PlatformDeviceTracker {
					trackers++
				}
			}
			if err := discovery.Validate(b); err != nil {
				var ve *discovery.ValidationError
				if errors.As(err, &ve) && !ve.Blocking() {
					t.Logf("%s: bundle %s: advisory: %v", sc.name, b.NodeID, err)
					continue
				}
				t.Errorf("%s: bundle %s is refused, so it would publish NO entities at all: %v",
					sc.name, b.NodeID, err)
			}
		}
	}
	if components != hamqttTotalConfigs {
		t.Errorf("bundles carry %d components, want %d", components, hamqttTotalConfigs)
	}
	const wantTrackers = 9
	if trackers != wantTrackers {
		t.Errorf("bundles carry %d device_tracker components, want %d", trackers, wantTrackers)
	}
	t.Logf("%d bundles, %d components, %d device_tracker components, all accepted",
		bundles, components, trackers)
}

// go-hamqtt v0.34.0's discovery.CheckBundleAvailability was weighed
// here and declined. It states, in the library's vocabulary, that no
// component may list an availability topic the consumer does not
// publish — measurement F8's trap, and the fix for two bridges in the
// fan-out that shipped a greyed-out fleet. This repository already
// asserts the same property, on the stronger side: TestAvailabilityModelIsTwoLevel
// requires every second availability source of every *published*
// config to be a topic the daemon wrote, and carries the 128/187 split
// as a literal. Written and mutation-tested rather than argued: the
// F8 mutation (hamqttLayout.Availability returning a dedicated
// "<uid>/availability" topic) is caught by five assertions, four of
// which predate any use of the new call, and the sixth added nothing.

// TestHamqttBundlesWithoutAnOriginAreRefused pins why the per-entity
// render passes a zero origin and the bundle form cannot.
//
// The zero origin is what keeps 315 payloads free of an `origin` block
// they do not carry today; a bundle with the same zero origin is
// refused outright. Both halves are load-bearing and they pull in
// opposite directions, so both are asserted.
func TestHamqttBundlesWithoutAnOriginAreRefused(t *testing.T) {
	t.Parallel()

	sc := surfaceScenarios()[2]
	bundles, err := scenarioDiscovery(t, sc).
		HamqttBundles(buildHamqttInputs(t, sc), discovery.Origin{})
	if err != nil {
		t.Fatalf("HamqttBundles: %v", err)
	}
	for _, b := range bundles {
		err := discovery.Validate(b)
		if err == nil {
			t.Errorf("bundle %s validates with no origin; step 7's origin block is no longer "+
				"a prerequisite for step 6 and the sequencing can be revisited", b.NodeID)
			continue
		}
		if !strings.Contains(err.Error(), "origin.name") {
			t.Errorf("bundle %s is refused for something other than the missing origin: %v",
				b.NodeID, err)
		}
	}
}

// TestHamqttPerEntityPayloadsCarryTheOrigin is the other half, on the
// bytes rather than on the validator.
//
// Step 4 asserted the opposite: the per-entity payloads carried no
// origin, because the shipped ones did not. F7 inverted it — every
// config on every plane now carries exactly {"name": "go-unifi2mqtt"},
// and nothing more, so the retained bytes do not move with the version
// the binary was linked at.
func TestHamqttPerEntityPayloadsCarryTheOrigin(t *testing.T) {
	t.Parallel()

	want := map[string]any{"name": hass.OriginName}
	seen := 0
	for _, sc := range surfaceScenarios() {
		comps, err := scenarioDiscovery(t, sc).RenderHamqtt(buildHamqttInputs(t, sc))
		if err != nil {
			t.Fatalf("RenderHamqtt: %v", err)
		}
		for _, c := range comps {
			var body map[string]any
			if err := json.Unmarshal(c.Body, &body); err != nil {
				t.Fatalf("decode %s: %v", c.Topic, err)
			}
			got, ok := body["origin"].(map[string]any)
			if !ok {
				t.Errorf("%s carries no origin block; a bundle of it would be refused", c.Topic)
				continue
			}
			if !reflect.DeepEqual(got, want) {
				t.Errorf("%s origin = %v, want %v", c.Topic, got, want)
			}
			seen++
			if _, ok := body["platform"]; ok {
				t.Errorf("%s carries a platform key, which belongs to the bundle form only", c.Topic)
			}
		}
	}
	if seen != hamqttTotalConfigs {
		t.Errorf("checked the origin on %d configs, want %d", seen, hamqttTotalConfigs)
	}
}

// --- the site device's two names ---------------------------------------

// TestHamqttSiteDeviceIsAnnouncedUnderOneName is F14, fixed.
//
// Step 4 found "unifi_site_default" announced as "UniFi Site Default"
// by the seven health entities, which took Site.Name, and as "UniFi
// Site default" by every SSID switch, which took Site.Internal. Per
// entity that was invisible last-write-wins in Home Assistant's device
// registry. A device bundle carries exactly ONE device block, so at
// step 6 one of the two would have won by collection order — which
// nothing stated, making the name a user sees a coin flip.
//
// Site.Name wins: Site.Internal is the API's addressing token and was
// never a display string. The SSID switches are the half that changes.
func TestHamqttSiteDeviceIsAnnouncedUnderOneName(t *testing.T) {
	t.Parallel()

	sc := surfaceScenarios()[2] // full.en: health and SSID switches both on
	d := scenarioDiscovery(t, sc)
	f := buildHamqttInputs(t, sc)

	if conflicts := d.HamqttDeviceBlockConflicts(f); len(conflicts) != 0 {
		t.Fatalf("device blocks still conflict on %d identities: %v", len(conflicts), conflicts)
	}

	// And the surviving name is the one F14 chose, on both planes —
	// "no conflict" would also be satisfied by both reading the wrong
	// field.
	const want = "UniFi Site Default"
	names := map[string]bool{}
	for _, e := range shippedSiteConfigs(t, d, f) {
		var body struct {
			Device struct {
				Name string `json:"name"`
			} `json:"device"`
		}
		if err := json.Unmarshal(e.Payload, &body); err != nil {
			t.Fatalf("decode %s: %v", e.ConfigTopic, err)
		}
		names[body.Device.Name] = true
	}
	if len(names) != 1 || !names[want] {
		t.Errorf("the site device is announced as %v, want exactly {%q}", sortedKeys(names), want)
	}
}

// shippedSiteConfigs returns every config the SHIPPED builders put on
// the synthetic site device: the health plane and the SSID switches,
// the two paths F14 made agree.
func shippedSiteConfigs(t *testing.T, d *hass.Discovery, f hass.HamqttFleet) []hass.Entry {
	t.Helper()
	out, err := d.Health()
	if err != nil {
		t.Fatalf("Health: %v", err)
	}
	if !f.ControlOpts.WLANEnable {
		t.Fatal("the scenario announces no SSID switches, so only one of the two paths is covered")
	}
	for i := range f.WLANs {
		e, err := d.WLANControl(&f.WLANs[i])
		if err != nil {
			t.Fatalf("WLANControl: %v", err)
		}
		out = append(out, e)
	}
	if len(out) < 8 {
		t.Fatalf("only %d site configs; both planes must be represented", len(out))
	}
	return out
}

// --- publishing nothing -------------------------------------------------

// failingPublisher fails the test on contact. Step 4 changes no publish
// path and nothing new reaches a broker; this is the assertion of that
// rather than a promise in a doc comment.
type failingPublisher struct{ t *testing.T }

func (f failingPublisher) Publish(
	_ context.Context, topic string, _ []byte, _ mqtt.QoS, _ bool, _ ...mqtt.PublishOption,
) error {
	f.t.Errorf("the go-hamqtt rendering path published to %s — step 4 publishes NOTHING", topic)
	return nil
}

func (f failingPublisher) Subscribe(
	_ context.Context, filter string, _ mqtt.QoS, _ mqtt.MessageHandler, _ ...mqtt.SubscribeOption,
) (mqtt.SubscribeResult, error) {
	f.t.Errorf("the go-hamqtt rendering path subscribed to %s", filter)
	return mqtt.SubscribeResult{}, nil
}

func (f failingPublisher) Unsubscribe(_ context.Context, _ string) error { return nil }

// TestHamqttRenderPathPublishesNothing drives every entry point the new
// path has against a transport that fails the test on contact.
func TestHamqttRenderPathPublishesNothing(t *testing.T) {
	t.Parallel()

	for _, sc := range surfaceScenarios() {
		f := buildHamqttInputs(t, sc)
		d := scenarioDiscovery(t, sc)
		if _, err := d.RenderHamqtt(f); err != nil {
			t.Fatalf("RenderHamqtt: %v", err)
		}
		if _, err := d.HamqttBundles(f, hamqttOrigin()); err != nil {
			t.Fatalf("HamqttBundles: %v", err)
		}
		d.HamqttDeviceBlockConflicts(f)
	}
}
