// SPDX-License-Identifier: MIT
// Copyright (C) 2026 SukramJ

package coordinator

import (
	"bytes"
	"context"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"flag"
	"fmt"
	"log/slog"
	"net/netip"
	"os"
	"path/filepath"
	"slices"
	"strings"
	"testing"
	"time"

	"github.com/SukramJ/go-unifi2mqtt/internal/config"
	"github.com/SukramJ/go-unifi2mqtt/internal/model"
	"github.com/SukramJ/go-unifi2mqtt/internal/unifi"
	"github.com/SukramJ/go-unifi2mqtt/internal/version"
)

// The published-surface pin (ADR 0070 phase 9, step 0).
//
// What this file captures is everything this daemon puts on a broker:
// every topic, the payload, the QoS and the retain flag, in one row per
// message, for a handful of scenarios that between them reach every
// builder in the tree. It exists so the phase-9 migration onto
// go-hamqtt can be proved byte-equal rather than argued to be.
//
// Three properties make it load-bearing rather than decorative:
//
//   - The messages come from the real coordinator driving the real
//     internal/hass builders. Only the console (Source) and the broker
//     (Publisher) are stubbed; nothing that composes a topic or a
//     payload is.
//   - QoS and retain are read off the transport call, not off a
//     constant, so a change to what publishConfig passes shows up here
//     even if the constant it was named after did not move.
//   - The digests in goldenDigests are held outside the golden files
//     and -update-surface-golden deliberately never writes them: a
//     golden regenerated by the very code it guards is invisible to the
//     run that regenerates it, so the only thing that can make a
//     regeneration visible is a value a human has to paste in.
//
// See notes/adr0070-phase9-measurement.md for what was measured here.

var updateSurfaceGolden = flag.Bool("update-surface-golden", false,
	"rewrite internal/coordinator/testdata/surface/*.json, print the new digests and fail")

// versionPlaceholder stands in for version.Version in the bridge info
// payload. It is the one value in the surface that moves with every
// release for reasons that have nothing to do with the published shape,
// and pinning it would make every version bump rewrite the goldens.
const versionPlaceholder = "<bridge-version>"

// recordedMsg is one publish: topic, delivery guarantee and payload in
// a single row, so a topic move, a payload change and a QoS/retain
// change are all one diff.
//
// The payload is stored decoded — JSON as JSON, scalars as text — so a
// reviewer reads the config rather than an escaped blob, and so the
// comparison can be made on a canonical re-encoding that is immune to
// key order and line endings.
type recordedMsg struct {
	Topic  string         `json:"topic"`
	QoS    int            `json:"qos"`
	Retain bool           `json:"retain"`
	JSON   map[string]any `json:"json,omitempty"`
	Text   *string        `json:"text,omitempty"`
	Empty  bool           `json:"empty,omitempty"`
}

// surfaceDoc is one scenario's whole published surface.
type surfaceDoc struct {
	Scenario string        `json:"scenario"`
	Messages []recordedMsg `json:"messages"`
}

// --- scenarios -------------------------------------------------------

// surfaceScenario is one installation shape.
type surfaceScenario struct {
	name string
	// yaml is the operator config, on top of the shipped defaults.
	yaml string
	// caps lists the classic-layer capabilities that are live.
	caps []unifi.Capability
	// devices/details/clients/wlans/health replace the defaults when set.
	setup func(s *fakeSource)
}

// capSet is a Capabilities over a fixed list.
type capSet map[unifi.Capability]bool

func (c capSet) Has(x unifi.Capability) bool { return c[x] }

const baseYAML = `
HOST: 192.0.2.1
API_KEY: k
MQTT_SERVER: broker
MQTT_TOPIC: unifi
HASS_ENABLE: true
`

func surfaceScenarios() []surfaceScenario {
	all := []unifi.Capability{
		unifi.CapHealth, unifi.CapClientDetails, unifi.CapPortPower,
		unifi.CapClientBlock, unifi.CapDeviceLocate, unifi.CapWLANToggle,
	}
	full := `
CLASSIC_ENABLE: true
CLASSIC_USERNAME: u
CLASSIC_PASSWORD: p
CLIENTS:
  ENABLE: true
  TYPES: [WIRELESS, WIRED]
  EXCLUDE_GUESTS: false
  SIGNAL_SENSOR: true
CONTROLS:
  ENABLE: true
  DEVICE_RESTART: true
  PORT_POWER_CYCLE: true
  GUEST_AUTHORIZE: true
  DEVICE_LOCATE: true
  CLIENT_BLOCK: true
  WLAN_ENABLE: true
`
	return []surfaceScenario{
		{name: "minimal.en", yaml: baseYAML, setup: surfaceDefaults},
		{name: "minimal.de", yaml: baseYAML + "LANGUAGE: de\n", setup: surfaceDefaults},
		{name: "full.en", yaml: baseYAML + full, caps: all, setup: surfaceDefaults},
		{name: "full.de", yaml: baseYAML + full + "LANGUAGE: de\n", caps: all, setup: surfaceDefaults},
		{name: "nonascii.de", yaml: baseYAML + full + "LANGUAGE: de\n", caps: all, setup: surfaceNonASCII},
	}
}

var (
	surfGwMAC  = model.MustParseMAC("00:00:5e:00:53:01")
	surfSwMAC  = model.MustParseMAC("00:00:5e:00:53:02")
	surfApMAC  = model.MustParseMAC("00:00:5e:00:53:03")
	surfPhone  = model.MustParseMAC("00:00:5e:00:53:11")
	surfNAS    = model.MustParseMAC("00:00:5e:00:53:12")
	surfGuest  = model.MustParseMAC("00:00:5e:00:53:13")
	surfOldMAC = model.MustParseMAC("00:00:5e:00:53:04")
	surfVPNKey = "vpn-client-uuid"
)

// surfaceDevices is the infrastructure fleet: a gateway, a PoE switch
// with a PoE port, a non-PoE SFP+ port and an offline dual-radio AP.
// Between them they reach every branch of deviceSpecs, portSpecs and
// radioSpecs.
func surfaceDevices() []model.Device {
	return []model.Device{
		{
			MAC: surfGwMAC, ID: "id-gw", ClassicID: "cid-gw", Name: "Gateway",
			Model: "UCG-Ultra", Type: model.DeviceGateway, State: model.DeviceOnline,
			IP: netip.MustParseAddr("192.0.2.1"), Supported: true, Firmware: "4.3.6",
			AdoptedAt: time.Date(2025, 1, 2, 3, 4, 5, 0, time.UTC),
		},
		{
			MAC: surfSwMAC, ID: "id-sw", ClassicID: "cid-sw", Name: "Switch Garage",
			Model: "USW-Pro-24-PoE", Type: model.DeviceSwitch, State: model.DeviceOnline,
			IP: netip.MustParseAddr("192.0.2.2"), Supported: true, Firmware: "7.0.25",
			UpdateAvail: true,
		},
		{
			MAC: surfApMAC, ID: "id-ap", ClassicID: "cid-ap", Name: "AP",
			Model: "U6-Pro", Type: model.DeviceAccessPoint, State: model.DeviceOnline,
			IP: netip.MustParseAddr("192.0.2.3"), Supported: true, Firmware: "6.6.55",
		},
		{
			// Offline, so refreshDeviceStats skips it: the five
			// statistics entities it still announces point at topics
			// that legitimately receive nothing until it comes back,
			// which is what the second availability level is for.
			MAC: surfOldMAC, ID: "id-old", ClassicID: "cid-old", Name: "Old AP",
			Model: "UAP-AC-Pro", Type: model.DeviceAccessPoint, State: model.DeviceOffline,
			Supported: false, Firmware: "5.43.56", UpdateAvail: true,
		},
	}
}

func surfaceDetails(devices []model.Device) []model.Device {
	d := slices.Clone(devices)
	d[1].UplinkID, d[1].UplinkMAC = "id-gw", surfGwMAC
	d[1].Ports = []model.Port{
		{
			Idx: 1, State: model.PortUp, Connector: "RJ45", SpeedMbps: 1000, MaxSpeedMbps: 1000,
			PoE: &model.PoEState{Enabled: true, Standard: "802.3at", Type: 2, State: "UP", PowerW: 6.5},
		},
		{Idx: 25, State: model.PortDown, Connector: "SFPPLUS", SpeedMbps: 0, MaxSpeedMbps: 10000},
	}
	d[2].UplinkID, d[2].UplinkMAC = "id-sw", surfSwMAC
	d[2].Radios = []model.Radio{
		{FrequencyGHz: 2.4, Channel: 6, ChannelWidth: 20, Standard: "802.11ax"},
		{FrequencyGHz: 5, Channel: 36, ChannelWidth: 80, Standard: "802.11ax"},
	}
	return d
}

func surfaceDefaults(s *fakeSource) {
	devices := surfaceDevices()
	s.devices = devices
	s.details = surfaceDetails(devices)
	s.wlans = []model.WLAN{
		{ID: "wlan-1", Name: "HomeNet", Enabled: true},
		{ID: "wlan-2", Name: "IoT", Enabled: false},
	}
	s.networks = []model.Network{{
		ID: "net-1", Name: "LAN", VLAN: 1, Enabled: true, Default: true,
		Subnets: []netip.Prefix{netip.MustParsePrefix("192.0.2.0/24")},
	}}
	s.stats["id-gw"] = model.DeviceStats{
		Uptime: 864000 * time.Second, CPUPct: 12.5, MemoryPct: 48,
		UplinkTxBps: 1048576, UplinkRxBps: 2097152,
	}
	s.stats["id-sw"] = model.DeviceStats{
		Uptime: 3600 * time.Second, CPUPct: 5, MemoryPct: 30,
		UplinkTxBps: 512, UplinkRxBps: 1024,
	}
	s.stats["id-ap"] = model.DeviceStats{
		Uptime: 7200 * time.Second, CPUPct: 9.75, MemoryPct: 61,
		UplinkTxBps: 4096, UplinkRxBps: 8192,
		RadioTxRetry: map[float64]float64{5: 1.2, 2.4: 0.4},
	}
	s.clients = surfaceClients()
	s.health = surfaceHealth()
}

func surfaceClients() []model.Client {
	lat := 12
	_ = lat
	return []model.Client{
		{
			MAC: surfPhone, ID: "id-phone", Name: "Phone", Type: model.ClientWireless,
			IP: netip.MustParseAddr("192.0.2.50"), UplinkID: "id-ap", SSID: "HomeNet",
			SignalDBm: -54, Network: "LAN", VLAN: 1,
			ConnectedAt: time.Date(2026, 8, 14, 9, 0, 0, 0, time.UTC),
		},
		{
			MAC: surfNAS, ID: "id-nas", Name: "NAS", Type: model.ClientWired,
			IP: netip.MustParseAddr("192.0.2.60"), UplinkID: "id-sw",
			Network: "LAN", VLAN: 1, Blocked: true,
		},
		{
			MAC: surfGuest, ID: "id-guest", Name: "Guest Tablet", Type: model.ClientWireless,
			IP: netip.MustParseAddr("192.0.2.70"), UplinkID: "id-ap", SSID: "IoT",
			IsGuest: true, SignalDBm: -71, Network: "LAN", VLAN: 1,
		},
		{
			// No MAC: a VPN client keys on the API UUID instead, which is
			// the branch model.Client.Key falls through to.
			ID: surfVPNKey, Name: "Roadwarrior", Type: model.ClientVPN,
			IP: netip.MustParseAddr("192.0.2.80"), Network: "LAN", VLAN: 1,
		},
	}
}

func surfaceHealth() model.Health {
	latency := 14
	uptime := int64(864000)
	return model.Health{
		WAN:   model.SubsystemHealth{Status: "ok"},
		LAN:   model.SubsystemHealth{Status: "ok"},
		WLAN:  model.SubsystemHealth{Status: "warning"},
		VPN:   model.SubsystemHealth{Status: "unknown"},
		WANIP: netip.MustParseAddr("198.51.100.7"),

		LatencyMs: &latency, UptimeSec: &uptime,
		RxBps: 12345678, TxBps: 2345678,
		NumUser: 40, NumGuest: 3, NumIoT: 7,
		NumAP: 2, NumSwitch: 1, NumGateway: 1,
	}
}

// surfaceNonASCII is the same installation with the names an operator
// in a German household actually uses: umlauts, an eszett and hyphens.
// It is what makes the slug divergence in §3.3 of the measurement
// visible in a golden rather than only in a unit test.
func surfaceNonASCII(s *fakeSource) {
	surfaceDefaults(s)
	devices := surfaceDevices()
	devices[0].Name = "Büro-Gateway"
	devices[1].Name = "Switch Küche"
	devices[2].Name = "Außengerät"
	devices[3].Name = "Groß-AP"
	s.devices = devices
	s.details = surfaceDetails(devices)
	clients := surfaceClients()
	clients[0].Name = "Märkus' Händy"
	clients[1].Name = "Groß-NAS"
	clients[2].Name = ""
	s.clients = clients
	s.wlans = []model.WLAN{
		{ID: "wlan-1", Name: "Süd-WLAN", Enabled: true},
		{ID: "wlan-2", Name: "Gäste", Enabled: false},
	}
}

// --- driving the real builders ---------------------------------------

// buildSurface runs one scenario through the real coordinator and
// returns every message it published.
//
// Nothing between the console and the broker is replaced: the
// coordinator composes the topics, internal/hass renders the payloads,
// and publish.go decides the QoS and the retain flag.
func buildSurface(t *testing.T, sc surfaceScenario) surfaceDoc {
	t.Helper()

	cfg, err := config.Load(strings.NewReader(sc.yaml), config.MapEnv{})
	if err != nil {
		t.Fatalf("scenario %s: config: %v", sc.name, err)
	}

	src := newFakeSource()
	sc.setup(src)
	if !cfg.ClassicEnable {
		// Without the classic layer the facade reports the health
		// endpoint as absent, which is what keeps the site entities
		// unannounced.
		src.healthErr = unifi.ErrCapabilityUnavailable
	}

	caps := capSet{}
	for _, c := range sc.caps {
		caps[c] = true
	}

	broker := &fakeBroker{}
	clock := newFakeClock()
	c := New(Deps{
		Cfg:          cfg,
		Site:         model.Site{ID: "site-uuid", Name: "Default", Internal: "default"},
		Source:       src,
		MQTT:         broker,
		Capabilities: caps,
		Info:         model.ControllerInfo{ApplicationVersion: "10.5.67"},
		Logger:       slog.New(slog.DiscardHandler),
		Now:          clock.now,
	})

	ctx := context.Background()
	// The order the daemon itself uses: the connect hook, then the
	// static loop (which announces discovery), then the fast loops.
	c.OnConnect(ctx)
	if err := c.refreshStatic(ctx); err != nil {
		t.Fatalf("scenario %s: refreshStatic: %v", sc.name, err)
	}
	if err := c.refreshDevices(ctx); err != nil {
		t.Fatalf("scenario %s: refreshDevices: %v", sc.name, err)
	}
	if err := c.refreshDeviceStats(ctx); err != nil {
		t.Fatalf("scenario %s: refreshDeviceStats: %v", sc.name, err)
	}
	// Gated exactly as Run gates them, so a scenario cannot publish a
	// plane its config would not have started a loop for.
	if cfg.Clients.Enable {
		if err := c.refreshClients(ctx); err != nil {
			t.Fatalf("scenario %s: refreshClients: %v", sc.name, err)
		}
	}
	if cfg.ClassicEnable {
		if err := c.refreshHealth(ctx); err != nil {
			t.Fatalf("scenario %s: refreshHealth: %v", sc.name, err)
		}
	}

	return surfaceDoc{Scenario: sc.name, Messages: recordMessages(t, broker)}
}

// recordMessages turns the recorded publishes into golden rows, sorted
// by topic so a concurrent stats fan-out cannot reorder the document.
func recordMessages(t *testing.T, b *fakeBroker) []recordedMsg {
	t.Helper()
	b.mu.Lock()
	msgs := slices.Clone(b.msgs)
	b.mu.Unlock()

	out := make([]recordedMsg, 0, len(msgs))
	for _, m := range msgs {
		row := recordedMsg{Topic: m.topic, QoS: int(m.qos), Retain: m.retain}
		payload := m.payload
		switch {
		case payload == "":
			row.Empty = true
		case strings.HasPrefix(payload, "{"):
			var obj map[string]any
			if err := json.Unmarshal([]byte(payload), &obj); err != nil {
				t.Fatalf("payload on %s is not JSON: %v", m.topic, err)
			}
			if v, ok := obj["bridge_version"]; ok && v == version.Version {
				obj["bridge_version"] = versionPlaceholder
			}
			row.JSON = obj
		default:
			text := payload
			row.Text = &text
		}
		out = append(out, row)
	}
	slices.SortStableFunc(out, func(a, b recordedMsg) int { return strings.Compare(a.Topic, b.Topic) })
	return out
}

// --- the golden test -------------------------------------------------

func TestPublishedSurfaceGolden(t *testing.T) {
	t.Parallel()

	if *updateSurfaceGolden {
		regenerateSurfaceGoldens(t)
		return
	}

	for _, sc := range surfaceScenarios() {
		t.Run(sc.name, func(t *testing.T) {
			t.Parallel()
			got := canonical(t, buildSurface(t, sc))
			want, err := os.ReadFile(surfaceGoldenPath(sc.name))
			if err != nil {
				t.Fatalf("read golden: %v (run with -update-surface-golden)", err)
			}
			var stored surfaceDoc
			if err := json.Unmarshal(want, &stored); err != nil {
				t.Fatalf("golden is not valid JSON: %v", err)
			}
			// Compared on canonical re-encoding, so key order,
			// indentation and line endings cannot decide the result.
			if !bytes.Equal(got, canonical(t, stored)) {
				t.Errorf("published surface changed for %s\n--- got\n%s", sc.name, got)
			}
		})
	}
}

// TestPublishedSurfaceDigests is what makes a regeneration visible.
//
// The digest is taken over the canonical encoding of the *rebuilt*
// scenario, not over the golden file's bytes, so it is immune to
// checkout differences as well as to reformatting — and it lives here,
// in Go, where -update-surface-golden cannot reach it.
func TestPublishedSurfaceDigests(t *testing.T) {
	t.Parallel()
	for _, sc := range surfaceScenarios() {
		t.Run(sc.name, func(t *testing.T) {
			t.Parallel()
			got := surfaceDigest(t, buildSurface(t, sc))
			want, ok := goldenDigests[sc.name]
			if !ok {
				t.Fatalf("no digest recorded for %s: got %s", sc.name, got)
			}
			if got != want {
				t.Errorf("surface digest for %s changed\n got: %s\nwant: %s\n"+
					"If this is intended, regenerate the goldens, review the diff, "+
					"and paste the new literal into goldenDigests in the same commit.",
					sc.name, got, want)
			}
		})
	}
}

func surfaceDigest(t *testing.T, doc surfaceDoc) string {
	t.Helper()
	sum := sha256.Sum256(canonical(t, doc))
	return hex.EncodeToString(sum[:])
}

// canonical re-encodes a document through encoding/json, which sorts
// object keys, so two semantically identical documents produce
// identical bytes.
func canonical(t *testing.T, doc surfaceDoc) []byte {
	t.Helper()
	b, err := json.MarshalIndent(doc, "", "  ")
	if err != nil {
		t.Fatalf("encode: %v", err)
	}
	return append(b, '\n')
}

func surfaceGoldenPath(name string) string {
	return filepath.Join("testdata", "surface", name+".json")
}

// regenerateSurfaceGoldens rewrites every golden, prints the digests
// and fails.
//
// The failure is the point: the digest map is not written, so a human
// has to paste the new literals in, in the same commit, whose message
// has to name the finding that moved the bytes.
func regenerateSurfaceGoldens(t *testing.T) {
	t.Helper()
	var b strings.Builder
	b.WriteString("goldens rewritten; paste these into goldenDigests:\n\n")
	b.WriteString("var goldenDigests = map[string]string{\n")
	for _, sc := range surfaceScenarios() {
		doc := buildSurface(t, sc)
		if err := os.WriteFile(surfaceGoldenPath(sc.name), canonical(t, doc), 0o600); err != nil {
			t.Fatalf("write golden: %v", err)
		}
		fmt.Fprintf(&b, "\t%q: %q,\n", sc.name, surfaceDigest(t, doc))
	}
	b.WriteString("}\n")
	t.Fatal(b.String())
}

// goldenDigests pins each scenario's canonical surface.
//
// Deliberately not written by -update-surface-golden. See
// [regenerateSurfaceGoldens].
var goldenDigests = map[string]string{
	"minimal.en":  "69dd1e5f60dd22c6666f25ef5b0307e75d7a7a4d39499259fe5ae5e83e4da915",
	"minimal.de":  "81ba397fb3f4d33201c92f67f2735908dbd554f458de99713f8098c9334f7b9f",
	"full.en":     "328d79ed687fc56c0a6bf0ed453cadf47ea31838a30a23ab947df5956354f75a",
	"full.de":     "778126942ff6585d7b89b50347cc11e2e1f7edded95d3d64ce971139a920a4d0",
	"nonascii.de": "dc1fea1bd8f34b3f7aedb96455a00dfb9f6a02e96480bce99cf0de246b650939",
}
